name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-audit:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Typecheck
        run: pnpm tsc -b --pretty false
      - name: Lint (non-blocking)
        run: pnpm lint
        continue-on-error: true
      - name: Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Rust checks (non-blocking)
        working-directory: src-tauri
        run: |
          cargo fmt --check
          cargo clippy -- -D warnings
          cargo install cargo-audit --locked || true
          cargo audit || true
        continue-on-error: true

