name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-windows:
    runs-on: windows-2025
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Install frontend deps
        run: pnpm install --frozen-lockfile
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install Tauri CLI
        run: pnpm dlx @tauri-apps/cli@^2 -v
      - name: Install WiX Toolset (for MSI)
        run: choco install wixtoolset --no-progress -y
      - name: Build app (tauri)
        run: pnpm run tauri:build
      - name: Upload artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: |
            src-tauri/target/**/bundle/msi/*.msi
            src-tauri/target/**/bundle/nsis/*.exe
            src-tauri/target/**/bundle/**/bundle.*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

